server:
  port: 7001
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false   #是否将自己注册到eureka中
    fetch-registry: false         #是否从eureka中获取信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      推荐这种写法 环境问题：${eureka.instance.hostname}  取出的是你自己电脑的计算机名称
#      defaultZone: http://127.0.0.1:7001/eureka/